### ISSUE TITLE
lua-classes branch: static declarations follow non-static declarations

### ISSUE THREAD

**Issue by pygy** [moai/moai-dev#439]
The branch fails to compile on my machine (OS X 10.6.8, Xcode 3.2.6, GCC 4.2)

I get the following errors:

moai-dev/xcode/libmoai/../../3rdparty/lua-5.1.3/src/lparser.c:1418:12: error: static declaration of 'namespaceload' follows non-static declaration

moai-dev/xcode/libmoai/../../3rdparty/lua-5.1.3/src/lparser.c:1594:12: error: static declaration of 'classload' follows non-static declaration

**Comment by patrickmeehan** [comment]
Don't think this branch is being developed/maintained any more.
